---
title: "Implemented Methods"
output: rmarkdown::html_vignette
bibliography: methods.bib
vignette: >
  %\VignetteIndexEntry{Methods}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

The package implements following methods

* @EngbertKliegl2003
* @Otero-Millan2014
* @NystromHolmqvist2010

Each methods has additional parameters that can be passed via `options` argument of `extract_saccades()` function.

## @EngbertKliegl2003
The algorithm labels a sample as a saccade if velocity, measured in units of its standard deviation (see below), exceeds a predefined threshold (defaults to $6$) and duration of a super-threshold period exceed a minimal duration (defaults to $12$ milliseconds). This method makes no assumptions about velocity in the units of degrees per second and can be used on any data (e.g., where samples encode gaze in screen position units).

The standard deviation is computed following a formula #2 in @EngbertKliegl2003 as
```r
sqrt(median(x^2) - median(x)^2)
```

However, if the value is smaller than [`.Machine$double.eps`](https://stat.ethz.ch/R-manual/R-devel/library/base/html/zMachine.html), it is recomputed via a mean estimator
```r
sqrt(mean(x^2) - mean(x)^2)
```

Only a monocular version of the algorithm is implemented with binocular saccades computed using overlapping votes from two eyes. For method details and rationale for default parameter values refer to @EngbertKliegl2003.

Parameters:

* `ek_velocity_threshold` Velocity threshold for saccade detection in standard deviations. Defaults to $6$.
* `ek_sd_fun` Function used to compute standard deviation for velociti0es. Defaults to `sd_via_median_estimator()` that implements formula #2 in @EngbertKliegl2003. Can be replaced with `sd()`, `mad()`, or a custom function.
* `ek_minimal_duration_ms` Minimal duration of a saccade in milliseconds. Defaults to $12$.
* `ek_minimal_separation_ms` A minimal required time gap between saccades. Defaults to $12$.

## @Otero-Millan2014
The algorithm:

1. Detects local peaks.
2. Filters them based on a minimal inter-peak interval (defaults to $30$ ms) and maximal allowed saccade rate (defaults to $5$ Hz).
3. Identifies onset and offset of a potential sacccade using an absolute velocity threshold in degrees per second.
4. Computes peak velocity and peak acceleration before and after the peak velocity was reached.
5. Rotates velocity and peak acceleration via PCA and retains components above a predefined threshold for explained variance.
6. Performs a cluster analysis on remaining components for $2$, $3$, $4$ picking the solution with the smallest silhouette. 
7. Saccades are identified as a cluster with highest average peak velocity.

For method details and rationale for default parameter values refer to @Otero-Millan2014.

Parameters:

* `om_minimal_inter_peak_time_ms` Minimal inter-peak interval in milliseconds. Defaults to $30$
* `om_maximal_peaks_per_second` Maximal allowed number of peaks per second. Defaults to $5$.
* `om_velocity_threshold_deg_per_sec` Threshold saccade velocity in °/s.  Defaults to $3$.
* `om_pca_variance_threshold` Minimal variance explained by retained rotated components. Defaults to $0.05$.

## @NystromHolmqvist2010




Below is a brief description of the method as implemented in the package, please refer to @EngbertKliegl2003 for rationale and further details.

1. Compute horizontal and vertical velocity components ($v_x$ and $v_y$), see [details](#ek-vel) below.
2. Compute standard deviation for velocity components ($\sigma_x$ and $\sigma_y$), see [details](#ek-sd) below.
3. Normalize velocity components so that they are in the units of velocity threshold $\lambda \cdot \ \sigma_{x/y}$, where by default $\lambda=6$ (`velocity_threshold` parameter): $v_{nx/ny} = \frac{v_{x/y}}{\lambda \cdot \ \sigma_{x/y}}$.
4. Compute normalized velocity $v_n = \sqrt{v_{nx}^2 + v_{ny}^2}$.
5. Flag samples that exceed threshold velocity $v_n > 1$.
6. Flag consecutive sequences of above-threshold samples as potential saccades.
7. Merge potential saccades that are less than `minimal_separation_ms` milliseconds apart. Note that this step is optional as it was _not used_ in @EngbertKliegl2003. Therefore by default `minimal_separation_ms = 0`, so no merging is performed.
8. Drop any potential saccades that are shorter than `minimal_duration_ms` milliseconds long. This parameter defaults to `minimal_duration_ms = 12` to match minimal duration of 3 samples (each 4 ms long) used in @EngbertKliegl2003.


### Standard deviation via median estimator {#ek-sd}
The standard deviation is computed following a formula 2 in @EngbertKliegl2003 as
```r
sqrt(median(x^2) - median(x)^2)
```

However, if the value is smaller than [`.Machine$double.eps`](https://stat.ethz.ch/R-manual/R-devel/library/base/html/zMachine.html), it is recomputed via a mean estimator
```r
sqrt(mean(x^2) - mean(x)^2)
```


## References
